// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkswjbpWD_UBrJCxz1LoJDbvvi9XY7g8U',
    appId: '1:205945878468:web:beb672e545560d2ee39691',
    messagingSenderId: '205945878468',
    projectId: 'medcapp-5f051',
    authDomain: 'medcapp-5f051.firebaseapp.com',
    storageBucket: 'medcapp-5f051.appspot.com',
    measurementId: 'G-T8YQCNDNH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_bTIx4FtObtHzyDX_1-OViBSEhbJNyjE',
    appId: '1:205945878468:android:1f9f241edbb1b6fbe39691',
    messagingSenderId: '205945878468',
    projectId: 'medcapp-5f051',
    storageBucket: 'medcapp-5f051.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUtxtvmWtDuQK7hxO0diaWPvlhY9GlcR4',
    appId: '1:205945878468:ios:add3e0e09cc57f7ee39691',
    messagingSenderId: '205945878468',
    projectId: 'medcapp-5f051',
    storageBucket: 'medcapp-5f051.appspot.com',
    androidClientId: '205945878468-u38a86um1r3tnt6k70e75a4bb37oi390.apps.googleusercontent.com',
    iosClientId: '205945878468-8otuqtae2frithajoc7bonjjnob69u2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.drugApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUtxtvmWtDuQK7hxO0diaWPvlhY9GlcR4',
    appId: '1:205945878468:ios:add3e0e09cc57f7ee39691',
    messagingSenderId: '205945878468',
    projectId: 'medcapp-5f051',
    storageBucket: 'medcapp-5f051.appspot.com',
    androidClientId: '205945878468-u38a86um1r3tnt6k70e75a4bb37oi390.apps.googleusercontent.com',
    iosClientId: '205945878468-8otuqtae2frithajoc7bonjjnob69u2s.apps.googleusercontent.com',
    iosBundleId: 'com.example.drugApp',
  );
}
